export const FLORENCE_PROFILE = {
  id: "florence-dawn-of-lathander",
  displayName: "福伦斯",
  actorNames: ["福伦斯", "Florence"],
  theme: "洛山达晨曦",
  palette: ["金白", "晨曦蓝", "新生绿"],
  concept: "混乱善良的光明领域牧师，特效基调为晨曦、再生、圣火与金白色神圣指引。",
  effects: [
    {
      id: "guiding-bolt-dawn-star",
      label: "晨星指引",
      itemIds: ["kqKnpvgYIAGHmkfE"],
      itemNames: ["光导箭 Guiding Bolt", "光导箭", "Guiding Bolt"],
      sequence: "guidingBolt",
      category: "projectile",
      durationType: "instant",
      tier: 2,
      defaultEnabled: true,
      requiresTarget: true,
      crpMode: "overlay-safe",
      notes: "CRP 负责法术自动化，本模块只在结算后补一层金白色指引射线。"
    },
    {
      id: "healing-word-sunrise",
      label: "新生日冕",
      itemIds: ["0O3sg7TKCyPFoiXC"],
      itemNames: ["治愈真言 Healing Word", "治愈真言", "Healing Word"],
      sequence: "healingWord",
      tier: 2,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "治疗目标脚下绽放柔和晨光。"
    },
    {
      id: "radiance-of-the-dawn-halo",
      label: "黎明环冕",
      itemIds: ["yhKbIhfGRNZw8LTu"],
      itemNames: ["黎明曙光 Radiance of the Dawn", "黎明曙光", "Radiance of the Dawn"],
      sequence: "radianceOfTheDawn",
      category: "aura",
      durationType: "instant",
      tier: 3,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "以施法者为中心展开大范围晨曦冲击波。"
    },
    {
      id: "sacred-flame-sun-pillar",
      label: "圣阳坠火",
      itemIds: ["s8o3iLRGVIoWxxE3"],
      itemNames: ["圣火术 Sacred Flame", "圣火术", "Sacred Flame"],
      sequence: "sacredFlame",
      tier: 2,
      defaultEnabled: true,
      requiresTarget: true,
      crpMode: "overlay-safe",
      notes: "目标位置落下一道金白圣焰。"
    },
    {
      id: "light-candle-of-dawn",
      label: "曙光烛芯",
      itemIds: ["dreLGoBFlt2HtrOL"],
      itemNames: ["光亮术 Light", "光亮术", "Light"],
      sequence: "light",
      category: "aura",
      durationType: "sustained",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "只做短暂点亮演出，不修改 Foundry 光源数据。"
    },
    {
      id: "shield-of-faith-golden-aegis",
      label: "洛山达金盾",
      itemIds: ["qhSIg9FFNyE90vqk"],
      itemNames: ["虔诚护盾 Shield of Faith", "虔诚护盾", "Shield of Faith"],
      sequence: "shieldOfFaith",
      category: "defense",
      durationType: "sustained",
      tier: 2,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "CRP 负责效果，本模块只做护盾成形演出。"
    },
    {
      id: "guidance-morning-whisper",
      label: "晨祷低语",
      itemIds: ["caK5UzvFx0giwkZN"],
      itemNames: ["神导术 Guidance", "神导术", "Guidance"],
      sequence: "guidance",
      category: "healing",
      durationType: "sustained",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "轻量祝福光环，适合频繁使用。"
    },
    {
      id: "channel-divinity-dawn-reservoir",
      label: "晨曦圣储",
      itemIds: ["fFtQBozFZhMGc3uh"],
      itemNames: ["引导神力 Channel Divinity", "引导神力", "Channel Divinity"],
      sequence: "channelDivinity",
      tier: 2,
      defaultEnabled: true,
      ignoreAaGuard: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "通用引导神力演出：圣徽蓄光、晨星环绕，为后续神术爆发做铺垫。"
    },
    {
      id: "warding-flare-solar-flash",
      label: "日冕耀斑",
      itemIds: ["edbi7BwaUwLo0RbC"],
      itemNames: ["Warding Flare", "守护闪光"],
      sequence: "wardingFlare",
      tier: 2,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "反应类能力只添加短闪，不接管判定。"
    },
    {
      id: "hold-person-dawn-chain",
      label: "晨光锁印",
      itemIds: ["trmwf5vtNi22IcYU"],
      itemNames: ["定身类人 Hold Person", "定身类人", "Hold Person"],
      sequence: "holdPerson",
      category: "condition",
      durationType: "sustained",
      tier: 2,
      defaultEnabled: true,
      requiresTarget: true,
      crpMode: "overlay-safe",
      notes: "目标脚下形成金色束缚符文，CRP/Midi 仍负责豁免与状态。"
    },
    {
      id: "burning-hands-dawn-cone",
      label: "黎明火舌",
      itemIds: ["Bqjn3fYDM2SwixZz"],
      itemNames: ["燃烧之手 Burning Hands", "燃烧之手", "Burning Hands"],
      sequence: "burningHands",
      category: "template",
      durationType: "instant",
      templateType: "cone",
      tier: 2,
      defaultEnabled: false,
      requiresTarget: false,
      selfTarget: true,
      usesMeasuredTemplate: true,
      crpMode: "crp-animation-disabled",
      notes: "该法术已有 CRP 动画，默认不叠加，避免重复演出。"
    },
    {
      id: "faerie-fire-dawn-motes",
      label: "晨露妖火",
      itemIds: ["loQlndS19H6VAose"],
      itemNames: ["妖火 Faerie Fire", "妖火", "Faerie Fire"],
      sequence: "faerieFire",
      category: "condition",
      durationType: "sustained",
      tier: 2,
      defaultEnabled: false,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "crp-animation-disabled",
      notes: "该法术已有 CRP 动画，默认不叠加。"
    },
    {
      id: "scorching-ray-sun-lances",
      label: "三重日枪",
      itemIds: ["5iK7MggFAz47ATft"],
      itemNames: ["灼热射线 Scorching Ray", "灼热射线", "Scorching Ray"],
      sequence: "scorchingRay",
      tier: 2,
      defaultEnabled: false,
      requiresTarget: true,
      crpMode: "crp-animation-disabled",
      notes: "该法术已有 CRP 动画，默认不叠加。"
    },
    {
      id: "detect-magic-dawn-sight",
      label: "晨曦魔视",
      itemIds: ["aINarsR2YihJjtFE"],
      itemNames: ["侦测魔法 Detect Magic", "侦测魔法", "Detect Magic"],
      sequence: "detectMagic",
      category: "aura",
      durationType: "sustained",
      tier: 1,
      defaultEnabled: false,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "crp-animation-disabled",
      notes: "该法术已有 CRP 动画，默认不叠加。"
    },
    {
      id: "reputation-ledger-dawn-ledger",
      label: "晨辉名册",
      itemIds: ["zeEGZI9x5QUA6C5M"],
      itemNames: ["查询声望"],
      sequence: "scrollIntel",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "打开一枚轻量卷轴符印，用于声望与情报查询。"
    },
    {
      id: "today-paper-dawn-briefing",
      label: "晨报启封",
      itemIds: ["ZlvFONf0LMh6a5h1"],
      itemNames: ["今日报纸"],
      sequence: "scrollIntel",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "阅读报纸时出现短暂卷轴与洞察之眼。"
    },
    {
      id: "resourceful-sun-thread",
      label: "灵机晨线",
      itemIds: ["jydglvLQEHb98v5P"],
      itemNames: ["适应力 Resourceful", "适应力", "Resourceful"],
      sequence: "passiveSigil",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "资源补强类特性使用轻量晨曦符文。"
    },
    {
      id: "skillful-dawn-practice",
      label: "熟练晨训",
      itemIds: ["l8er43TZZvOhB0Tc"],
      itemNames: ["技能 Skillful", "技能", "Skillful"],
      sequence: "passiveSigil",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "被动熟练项只做面板预览与轻量符文。"
    },
    {
      id: "versatile-dawn-facet",
      label: "多面晨辉",
      itemIds: ["2DcqaAsjWQb7fQd0"],
      itemNames: ["多才多艺 Versatile", "多才多艺", "Versatile"],
      sequence: "passiveSigil",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "被动泛用能力使用一枚多面晨光符。"
    },
    {
      id: "alert-first-light",
      label: "先明警兆",
      itemIds: ["LfAq6ATekUTp7yLu"],
      itemNames: ["警戒 Alert", "警戒", "Alert"],
      sequence: "utilityPulse",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "警戒提示使用快速晨光脉冲。"
    },
    {
      id: "healer-dawn-triage",
      label: "急救晨光",
      itemIds: ["yIdW7En0DJUlchyR"],
      itemNames: ["医疗师 Healer", "医疗师", "Healer"],
      sequence: "healerKit",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "医疗师特性用柔和治疗环表现。"
    },
    {
      id: "spellcasting-dawn-vow",
      label: "施法圣约",
      itemIds: ["9YwbOGo2HIVnkZNl"],
      itemNames: ["施法 Spellcasting", "施法", "Spellcasting"],
      sequence: "passiveSigil",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "施法能力总览使用轻量圣徽预览。"
    },
    {
      id: "divine-order-dawn-office",
      label: "晨职授印",
      itemIds: ["9CBespM0dBDO1RDR"],
      itemNames: ["圣职 Divine Order", "圣职", "Divine Order"],
      sequence: "passiveSigil",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "圣职被动项使用授印式符文。"
    },
    {
      id: "thaumaturge-dawn-order",
      label: "奇术圣职",
      itemIds: ["3ZzLAISlrinTXqY7"],
      itemNames: ["圣职：奇术使 Divine Order: Thaumaturge", "圣职：奇术使", "Thaumaturge"],
      sequence: "passiveSigil",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "奇术使分支使用变化学派晨辉符。"
    },
    {
      id: "rations-road-sun",
      label: "旅粮补给",
      itemIds: ["Ie67MrkFzpLdPbEd"],
      itemNames: ["口粮 Rations", "口粮", "Rations"],
      sequence: "rationUse",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "消耗口粮时只给一枚极轻量暖光提示。"
    },
    {
      id: "holy-water-dawn-splash",
      label: "圣水破邪",
      itemIds: ["1eGXbTtdripLq8qj"],
      itemNames: ["圣水 Holy Water", "圣水", "Holy Water"],
      sequence: "holyWater",
      tier: 2,
      defaultEnabled: true,
      requiresTarget: true,
      crpMode: "overlay-safe",
      notes: "投掷圣水时在目标处做水花与圣光净化。"
    },
    {
      id: "dart-white-streak",
      label: "飞镖破空",
      itemIds: ["i2GvPVGXkfG3PLn5"],
      itemNames: ["飞镖 Dart", "飞镖", "Dart"],
      sequence: "dartThrow",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: true,
      crpMode: "overlay-safe",
      notes: "远程飞镖使用轻量物理投射线。"
    },
    {
      id: "thaumaturgy-dawn-wonder",
      label: "晨曦奇术",
      itemIds: ["cgkkE45bwyPPNgcW"],
      itemNames: ["奇术 Thaumaturgy", "奇术", "Thaumaturgy"],
      sequence: "utilityPulse",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "奇术用小范围神术脉冲表达，不接管具体效果。"
    },
    {
      id: "healers-kit-dawn-bandage",
      label: "绷带晨辉",
      itemIds: ["bDd1D2flIPj2XIsR"],
      itemNames: ["医疗包 Healer's Kit", "医疗包", "Healer's Kit"],
      sequence: "healerKit",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "医疗包稳定动作使用轻量治疗环。"
    },
    {
      id: "newcomer-beer-warm-light",
      label: "新人啤酒",
      itemIds: ["IenFvZf8jEVnygE4"],
      itemNames: ["新人啤酒"],
      sequence: "brewUse",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "饮用啤酒时给一枚暖色恢复提示。"
    },
    {
      id: "scroll-daylight-dawn-unfurl",
      label: "昼光卷轴",
      itemIds: ["MyWxTHNNYhYhXmQD"],
      itemNames: ["法术卷轴: 昼明术 Daylight", "昼明术", "Daylight"],
      sequence: "daylightScroll",
      category: "template",
      durationType: "sustained",
      templateType: "circle",
      tier: 2,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      usesMeasuredTemplate: true,
      crpMode: "overlay-safe",
      notes: "昼明术卷轴根据模板/目标展开柔和光域。"
    },
    {
      id: "shar-hideout-dawn-intel",
      label: "密报晨印",
      itemIds: ["lRoQQStOwEdCQRmG"],
      itemNames: ["莎尔秘密据点情报"],
      sequence: "scrollIntel",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "情报类物品使用卷轴与洞察之眼。"
    },
    {
      id: "see-invisibility-dawn-eye",
      label: "破隐晨视",
      itemIds: ["5aDbion62nZId6Ps"],
      itemNames: ["识破隐形 See Invisibility", "识破隐形", "See Invisibility"],
      sequence: "seeInvisibility",
      category: "aura",
      durationType: "sustained",
      tier: 2,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "识破隐形在施法者处展开洞察之眼。"
    },
    {
      id: "light-domain-spells-dawn-index",
      label: "光域圣卷",
      itemIds: ["puXi13GABarjkN6l"],
      itemNames: ["光明领域法术 Light Domain Spells", "光明领域法术", "Light Domain Spells"],
      sequence: "passiveSigil",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "领域法术总览使用轻量圣卷符。"
    },
    {
      id: "gentle-repose-dawn-seal",
      label: "静息圣封",
      itemIds: ["6tHh0lOgxxxr4he1"],
      itemNames: ["遗体防腐 Gentle Repose", "遗体防腐", "Gentle Repose"],
      sequence: "gentleRepose",
      tier: 2,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "遗体防腐使用静息封印与柔和守护光。"
    },
    {
      id: "midnight-tears-poison-drop",
      label: "午夜毒露",
      itemIds: ["hameB33nJXkoguMm"],
      itemNames: ["午夜之泪 Midnight Tears", "午夜之泪", "Midnight Tears"],
      sequence: "poisonUse",
      tier: 2,
      defaultEnabled: true,
      requiresTarget: true,
      crpMode: "overlay-safe",
      notes: "毒药使用绿色液体冲击与轻量毒素轨迹。"
    }
  ]
};
