export const GRACE_PROFILE = {
  id: "grace-arcane-frost-orbit",
  displayName: "格蕾丝",
  actorNames: ["格蕾丝", "Grace"],
  theme: "银蓝奥术冰环",
  palette: ["银蓝", "星屑白", "浅紫", "霜雾青"],
  concept: "学院派奥术施法者，特效基调为银蓝冰霜、星屑轨道、精密符文、镜像幻术与克制的传送残影。",
  effects: [
    {
      id: "reputation-arcane-ledger",
      label: "星页名册",
      itemIds: ["GJwN791SXLJ7K4o1"],
      itemNames: ["查询声望"],
      sequence: "graceArcaneStudy",
      category: "utility",
      durationType: "instant",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "用银蓝卷页和洞察符文表现声望查询。"
    },
    {
      id: "lucky-star-turn",
      label: "星轨转运",
      itemIds: ["88R1PgsgGS4uCAB6"],
      itemNames: ["幸运 Lucky", "幸运", "Lucky"],
      sequence: "graceLucky",
      category: "aura",
      durationType: "instant",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "短促星轨回旋，表现命运被轻轻拨动。"
    },
    {
      id: "resourceful-arcane-thread",
      label: "奥术线轴",
      itemIds: ["52TR88b8DQZxb8cK"],
      itemNames: ["适应力 Resourceful", "适应力", "Resourceful"],
      sequence: "graceArcaneUtility",
      category: "passive",
      durationType: "instant",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "资源补强类特性使用小型银蓝符文。"
    },
    {
      id: "skillful-arcane-practice",
      label: "学院熟练式",
      itemIds: ["5ueSIf24Xypq1v2w"],
      itemNames: ["技能 Skillful", "技能", "Skillful"],
      sequence: "graceArcaneUtility",
      category: "passive",
      durationType: "instant",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "被动熟练项使用轻量符文，主要用于面板预览。"
    },
    {
      id: "versatile-prismatic-note",
      label: "多面星注",
      itemIds: ["k1eG7vmKpNt33qMF"],
      itemNames: ["多才多艺 Versatile", "多才多艺", "Versatile"],
      sequence: "graceArcaneUtility",
      category: "passive",
      durationType: "instant",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "以多层星屑符号表现灵活的知识储备。"
    },
    {
      id: "skilled-library-index",
      label: "索引熟习",
      itemIds: ["bBdKJzJL6NB3Fcv4"],
      itemNames: ["熟习 Skilled", "熟习", "Skilled"],
      sequence: "graceArcaneStudy",
      category: "passive",
      durationType: "instant",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "被动熟习项用书页式奥术符号表现。"
    },
    {
      id: "alert-silver-warning",
      label: "银铃警兆",
      itemIds: ["XhhQAAMbI8SIhxFf"],
      itemNames: ["警戒 Alert", "警戒", "Alert"],
      sequence: "graceAlert",
      category: "passive",
      durationType: "instant",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "快速银蓝闪烁，提示预判与反应。"
    },
    {
      id: "ray-of-frost-crystal-line",
      label: "霜晶直线",
      itemIds: ["MSF7YQB9IpHlkjq4"],
      itemNames: ["冷冻射线 Ray of Frost", "冷冻射线", "Ray of Frost"],
      sequence: "graceRayOfFrost",
      category: "projectile",
      durationType: "instant",
      tier: 2,
      defaultEnabled: true,
      requiresTarget: true,
      crpMode: "overlay-safe",
      notes: "银蓝霜线命中后在目标脚下开出冰晶裂纹。"
    },
    {
      id: "dancing-lights-orbit",
      label: "星灯环舞",
      itemIds: ["2AwGGM5nLFO6kClG"],
      itemNames: ["舞光术 Dancing Lights", "舞光术", "Dancing Lights"],
      sequence: "graceDancingLights",
      category: "aura",
      durationType: "sustained",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "几枚蓝紫光点围绕施法者短暂成轨。"
    },
    {
      id: "spellcasting-arcane-grammar",
      label: "施法文法",
      itemIds: ["LwIjizGPSrmauQBv"],
      itemNames: ["施法 Spellcasting", "施法", "Spellcasting"],
      sequence: "graceArcaneUtility",
      category: "passive",
      durationType: "instant",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "施法能力总览使用轻量蓝色奥术环。"
    },
    {
      id: "ritual-adept-clockwork-circle",
      label: "仪式钟环",
      itemIds: ["PD9WSVxr4FMm6xkt"],
      itemNames: ["仪式学家 Ritual Adept", "仪式学家", "Ritual Adept"],
      sequence: "graceRitualAdept",
      category: "passive",
      durationType: "instant",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "仪式类能力以缓慢展开的星页和法阵表现。"
    },
    {
      id: "arcane-recovery-star-reservoir",
      label: "星辉回想",
      itemIds: ["o1Ii9p6o72W4zbZJ"],
      itemNames: ["奥术回想 Arcane Recovery", "奥术回想", "Arcane Recovery"],
      sequence: "graceArcaneRecovery",
      category: "passive",
      durationType: "instant",
      tier: 2,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "以星屑回流与法阵蓄能表现法术位恢复。"
    },
    {
      id: "dagger-silver-arc",
      label: "银刃弧线",
      itemIds: ["9fQasqwJADKs1lT1", "TZigdQPSwJM83FoK"],
      itemNames: ["匕首 Dagger", "匕首", "Dagger"],
      sequence: "graceDagger",
      category: "weapon",
      durationType: "instant",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: true,
      crpMode: "overlay-safe",
      notes: "匕首攻击只给轻量银蓝刃线，不遮挡武器判定。"
    },
    {
      id: "staff-arcane-tap",
      label: "法杖点星",
      itemIds: ["uQVzAQoDxhWY4ETb"],
      itemNames: ["法杖 Staff", "法杖", "Staff"],
      sequence: "graceStaff",
      category: "weapon",
      durationType: "instant",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: true,
      crpMode: "overlay-safe",
      notes: "法杖攻击附带小型奥术冲击。"
    },
    {
      id: "ink-scholar-mark",
      label: "银墨落款",
      itemIds: ["tRPhjQunilpPU7BZ"],
      itemNames: ["墨水 Ink", "墨水", "Ink"],
      sequence: "graceArcaneStudy",
      category: "utility",
      durationType: "instant",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "墨水使用时浮现简短书写符文。"
    },
    {
      id: "oil-alchemy-glint",
      label: "炼油微光",
      itemIds: ["KgfHGxZU7G1WIR8Y"],
      itemNames: ["燃油 Oil", "燃油", "Oil"],
      sequence: "graceAlchemy",
      category: "utility",
      durationType: "instant",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "炼金消耗品使用浅色液体和小型符文提示。"
    },
    {
      id: "prestidigitation-prism-trick",
      label: "棱镜小戏法",
      itemIds: ["6bNwukIC90kLLARg"],
      itemNames: ["魔法伎俩 Prestidigitation", "魔法伎俩", "Prestidigitation"],
      sequence: "gracePrestidigitation",
      category: "utility",
      durationType: "instant",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "用小型星灯、幻术环与蓝紫闪光表现随手戏法。"
    },
    {
      id: "find-familiar-starlit-summon",
      label: "星使召来",
      itemIds: ["XuY0hRpMAjqfwPw8"],
      itemNames: ["寻获魔宠 Find Familiar", "寻获魔宠", "Find Familiar"],
      sequence: "graceFindFamiliar",
      category: "summon",
      durationType: "sustained",
      tier: 2,
      defaultEnabled: false,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "crp-animation-disabled",
      notes: "该法术已有 CRP 动画，默认不叠加；启用本库时只关闭 CRP 动画，不影响召唤自动化。"
    },
    {
      id: "comprehend-languages-star-lexicon",
      label: "星文译典",
      itemIds: ["kdODN849gdjvWJmx"],
      itemNames: ["通晓语言 Comprehend Languages", "通晓语言", "Comprehend Languages"],
      sequence: "graceComprehendLanguages",
      category: "aura",
      durationType: "sustained",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "一圈蓝色译文环绕角色展开。"
    },
    {
      id: "sleep-lunar-drift",
      label: "月眠星尘",
      itemIds: ["bnzUfvS3AohDiVn5"],
      itemNames: ["睡眠术 Sleep", "睡眠术", "Sleep"],
      sequence: "graceSleep",
      category: "condition",
      durationType: "sustained",
      tier: 2,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "对选中目标或施法者周围铺开蓝紫睡眠云与符号。"
    },
    {
      id: "unseen-servant-arcane-hand",
      label: "无形侍手",
      itemIds: ["hSUjOokEoXllWv3R"],
      itemNames: ["隐形仆役 Unseen Servant", "隐形仆役", "Unseen Servant"],
      sequence: "graceUnseenServant",
      category: "summon",
      durationType: "sustained",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "以透明奥术手和召唤圆表现仆役出现。"
    },
    {
      id: "mage-armor-silver-ward",
      label: "银蓝法甲",
      itemIds: ["BlU4tQEKWdYW7GE8"],
      itemNames: ["法师护甲 Mage Armor", "法师护甲", "Mage Armor"],
      sequence: "graceMageArmor",
      category: "defense",
      durationType: "sustained",
      tier: 2,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "蓝色奥术护盾贴身成形，不修改实际 AC 自动化。"
    },
    {
      id: "magic-missile-constellation-barrage",
      label: "星矢齐发",
      itemIds: ["XXXLZMG1sIVwpWax"],
      itemNames: ["魔法飞弹", "Magic Missile"],
      sequence: "graceMagicMissile",
      category: "projectile",
      durationType: "instant",
      tier: 2,
      defaultEnabled: false,
      requiresTarget: true,
      crpMode: "crp-animation-disabled",
      notes: "该法术已有 CRP 动画，默认不叠加；启用本库时改用多枚星矢。"
    },
    {
      id: "newcomer-beer-arcane-toast",
      label: "星杯小酌",
      itemIds: ["buoxqU4K1d2cjv2U"],
      itemNames: ["新人啤酒"],
      sequence: "graceBrew",
      category: "utility",
      durationType: "instant",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "啤酒使用时只做一枚极轻量星屑提示。"
    },
    {
      id: "silvered-weapon-moon-edge",
      label: "月银镀刃",
      itemIds: ["Rl2MU5jENMLd772G"],
      itemNames: ["镀银武器 Silvered Weapon", "镀银武器", "Silvered Weapon"],
      sequence: "graceSilveredWeapon",
      category: "utility",
      durationType: "instant",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "武器镀银时出现短暂月银反光。"
    },
    {
      id: "scholar-star-margin",
      label: "学者星注",
      itemIds: ["p7TDH2YKpxMSeDDN"],
      itemNames: ["学者 Scholar", "学者", "Scholar"],
      sequence: "graceArcaneStudy",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "学者背景用书页与星注表现。"
    },
    {
      id: "tasha-laughter-mirror-mask",
      label: "塔莎镜笑",
      itemIds: ["T7ryGO1sO2rQCEw5"],
      itemNames: ["塔莎狂笑术 Tasha's Hideous Laughter", "塔莎狂笑术", "Tasha's Hideous Laughter"],
      sequence: "graceTashaLaughter",
      category: "condition",
      durationType: "sustained",
      tier: 2,
      defaultEnabled: true,
      requiresTarget: true,
      crpMode: "overlay-safe",
      notes: "目标处浮现镜面面具与蓝紫惑控环。"
    },
    {
      id: "disguise-self-mirror-veil",
      label: "镜幕易容",
      itemIds: ["4cp6whumu0DgW06c"],
      itemNames: ["易容术 Disguise Self", "易容术", "Disguise Self"],
      sequence: "graceDisguiseSelf",
      category: "aura",
      durationType: "sustained",
      tier: 2,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "以幻术圆和镜面星屑表现外貌重叠。"
    },
    {
      id: "evocation-savant-blue-formula",
      label: "塑能蓝式",
      itemIds: ["iVnmAD8HhyIpyUId"],
      itemNames: ["塑能学者 Evocation Savant", "塑能学者", "Evocation Savant"],
      sequence: "graceEvocationSavant",
      category: "passive",
      durationType: "instant",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "塑能学派被动项用蓝色塑能符号预览。"
    },
    {
      id: "potent-cantrip-crystal-amplifier",
      label: "戏法增幅晶",
      itemIds: ["Dr1IeX5itd0Ho1V6"],
      itemNames: ["强力戏法 Potent Cantrip Potent Cantrip", "强力戏法", "Potent Cantrip"],
      sequence: "gracePotentCantrip",
      category: "passive",
      durationType: "instant",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "被动戏法增幅用冰晶与塑能符号表现。"
    },
    {
      id: "misty-step-star-fold",
      label: "星雾折步",
      itemIds: ["nEVwncgxufZ9KBy0"],
      itemNames: ["迷踪步 Misty Step", "迷踪步", "Misty Step"],
      sequence: "graceMistyStep",
      category: "utility",
      durationType: "instant",
      tier: 2,
      defaultEnabled: false,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "crp-animation-disabled",
      notes: "该法术已有 CRP 动画，默认不叠加；启用本库时只关闭 CRP 动画，不影响位移自动化。"
    },
    {
      id: "identify-arcane-prism",
      label: "鉴定棱镜",
      itemIds: ["7BD59Az2LLgP3kUN"],
      itemNames: ["鉴定术 Identify", "鉴定术", "Identify"],
      sequence: "graceIdentify",
      category: "aura",
      durationType: "sustained",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "鉴定时展开棱镜和洞察之眼。"
    },
    {
      id: "today-paper-star-briefing",
      label: "晨报星批",
      itemIds: ["1xPXPJtNb9bHg17t"],
      itemNames: ["今日报纸"],
      sequence: "graceArcaneStudy",
      category: "utility",
      durationType: "instant",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "阅读报纸时浮现短暂蓝色批注。"
    },
    {
      id: "midnight-tears-violet-drop",
      label: "午夜紫露",
      itemIds: ["9rhJtHbFyEE7pjrC"],
      itemNames: ["午夜之泪 Midnight Tears", "午夜之泪", "Midnight Tears"],
      sequence: "graceMidnightTears",
      category: "condition",
      durationType: "instant",
      tier: 2,
      defaultEnabled: true,
      requiresTarget: true,
      crpMode: "overlay-safe",
      notes: "毒药使用以紫绿色液体冲击表现，保持判定交给系统。"
    },
    {
      id: "magical-berries-starlit-bloom",
      label: "星莓绽光",
      itemIds: ["mIUmW9T1rc9Xdh1Z"],
      itemNames: ["神莓 Magical Berries", "神莓", "Magical Berries"],
      sequence: "graceMagicalBerries",
      category: "healing",
      durationType: "instant",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "神莓使用时给一枚绿蓝恢复星光。"
    },
    {
      id: "shield-instant-silver-ward",
      label: "瞬发银盾",
      itemIds: ["myqxMi3mr5hOc0qM"],
      itemNames: ["护盾术 Shield", "护盾术", "Shield"],
      sequence: "graceShield",
      category: "defense",
      durationType: "instant",
      tier: 2,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "反应护盾只播放瞬间护幕，不接管 AC 或反应消耗。"
    }
  ]
};
