export const LAWRENCE_PROFILE = {
  id: "lawrence-graveyard-warden",
  displayName: "L.",
  actorNames: ["L.", "L"],
  theme: "墓园石像守卫",
  palette: ["灰白石", "银辉", "旧金箔", "墓园尘雾"],
  concept: "由守墓雕像觉醒而来的战士，特效基调为沉重石质、银色壁垒、墓园尘雾与克制的武技冲击。",
  effects: [
    {
      id: "silver-bulwark-grave-rampart",
      label: "银辉壁垒",
      itemIds: ["mpQ5BMR0K6Ol5XxK"],
      itemNames: ["银辉壁垒 Silver Bulwark", "银辉壁垒", "Silver Bulwark"],
      sequence: "lawrenceBulwark",
      category: "defense",
      durationType: "sustained",
      tier: 2,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "以灰白石尘和银色盾墙表现守墓者的防御本能。"
    },
    {
      id: "paths-grace-stone-road",
      label: "石路恩泽",
      itemIds: ["gT0OHHXXxbG7BWU4"],
      itemNames: ["路途恩泽 Path’s Grace", "路途恩泽 Path's Grace", "路途恩泽", "Path’s Grace", "Path's Grace"],
      sequence: "lawrenceGrace",
      category: "aura",
      durationType: "sustained",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "脚下展开一圈折射银辉，像从墓园石径上重新起步。"
    },
    {
      id: "zealous-charge-gravebreaker",
      label: "破碑冲锋",
      itemIds: ["D6sdL1bWPl4HdCaq"],
      itemNames: ["狂热冲锋 Zealous Charge", "狂热冲锋", "Zealous Charge"],
      sequence: "lawrenceCharge",
      category: "weapon",
      durationType: "instant",
      tier: 2,
      defaultEnabled: true,
      requiresTarget: true,
      crpMode: "overlay-safe",
      notes: "冲锋线使用石尘拖尾、墓碑震荡和银辉冲击，保留光耀伤害提示。"
    },
    {
      id: "fighting-style-graven-stance",
      label: "石像战姿",
      itemIds: ["bGX2eQzb3Sa5BjHE"],
      itemNames: ["战斗风格 Fighting Style", "战斗风格", "Fighting Style"],
      sequence: "lawrenceUtility",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "被动战斗风格用极轻量石尘符文，主要用于面板预览。"
    },
    {
      id: "second-wind-stone-breath",
      label: "石躯回气",
      itemIds: ["s8zCJIVD5osyWKpW"],
      itemNames: ["回气 Second Wind", "回气", "Second Wind"],
      sequence: "lawrenceSecondWind",
      tier: 2,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "治疗环被压成石像自我修补的质感。"
    },
    {
      id: "blind-fighting-empty-eye",
      label: "空眼盲斗",
      itemIds: ["0UlOyHGtBXqSH81v"],
      itemNames: ["战斗风格：盲斗 Fighting Style: Blind Fighting", "盲斗", "Blind Fighting"],
      sequence: "lawrenceHunter",
      category: "aura",
      durationType: "sustained",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "空洞宝石眼短暂亮起，用洞察之眼表现盲斗感知。"
    },
    {
      id: "hunter-of-hunters-grave-gaze",
      label: "猎手凝视",
      itemIds: ["EIDc2OeNocC8EHRw"],
      itemNames: ["猎兽猎手 Hunter of Hunters", "猎兽猎手", "Hunter of Hunters"],
      sequence: "lawrenceHunter",
      category: "condition",
      durationType: "sustained",
      tier: 2,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "若有选中目标，会在目标脚下打上锁链式猎手标记。"
    },
    {
      id: "greatsword-grave-arc",
      label: "墓卫巨剑",
      itemIds: ["PE7TgDt9bnRGJxEp"],
      itemNames: ["巨剑 Greatsword", "巨剑", "Greatsword"],
      sequence: "lawrenceGreatsword",
      tier: 2,
      defaultEnabled: true,
      requiresTarget: true,
      crpMode: "overlay-safe",
      notes: "重剑挥击后附一层灰白石尘冲击。"
    },
    {
      id: "flail-grave-chain",
      label: "墓链回响",
      itemIds: ["barEmXQ2vOcvEHXz"],
      itemNames: ["链枷 Flail", "链枷", "Flail"],
      sequence: "lawrenceFlail",
      tier: 2,
      defaultEnabled: true,
      requiresTarget: true,
      crpMode: "overlay-safe",
      notes: "链枷使用摆锤轨迹和延迟冲击，强调沉重回响。"
    },
    {
      id: "javelin-grave-marker",
      label: "标枪破碑",
      itemIds: ["cBjX3mohsE1GIBoS"],
      itemNames: ["标枪 Javelin", "标枪", "Javelin"],
      sequence: "lawrenceJavelin",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: true,
      crpMode: "overlay-safe",
      notes: "标枪投掷命中时带一层白色尘爆。"
    },
    {
      id: "piton-grave-nail",
      label: "墓钉固定",
      itemIds: ["vzkp2WewFfwjEBOu"],
      itemNames: ["岩钉 Piton", "岩钉", "Piton"],
      sequence: "lawrenceUtility",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "工具类物品使用低调石尘符文。"
    },
    {
      id: "torch-watchfire",
      label: "守墓火把",
      itemIds: ["U5cXuHQEdwHIELU4"],
      itemNames: ["火把 Torch", "火把", "Torch"],
      sequence: "lawrenceUtility",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "火把只做轻量提示，不修改 Foundry 光源数据。"
    },
    {
      id: "crowbar-stone-lever",
      label: "石隙撬动",
      itemIds: ["sEUlsEG2dQ5oxngu"],
      itemNames: ["撬棍 Crowbar", "撬棍", "Crowbar"],
      sequence: "lawrenceUtility",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "工具动作使用短促石尘与变化符文。"
    },
    {
      id: "rope-grave-tether",
      label: "墓绳牵引",
      itemIds: ["RmxzK7PXYMQKAEHA"],
      itemNames: ["麻绳（50尺）Hempen Rope (50 ft.)", "麻绳", "Hempen Rope"],
      sequence: "lawrenceUtility",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "绳索检定用轻量符文表示牵引和固定。"
    },
    {
      id: "waterskin-stone-canteen",
      label: "石壶清水",
      itemIds: ["dlP1bauerwotX43A"],
      itemNames: ["水袋 Waterskin", "水袋", "Waterskin"],
      sequence: "lawrenceUtility",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "补给物品只做低强度提示。"
    },
    {
      id: "rations-stone-journey",
      label: "石像旅粮",
      itemIds: ["VpVtMgvcEHATDR1p"],
      itemNames: ["口粮 Rations", "口粮", "Rations"],
      sequence: "rationUse",
      tier: 1,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "复用极轻量补给提示，避免消耗品演出过重。"
    },
    {
      id: "action-surge-stone-tide",
      label: "石潮再动",
      itemIds: ["Uk255Ak5Ddvyj9mC"],
      itemNames: ["动作如潮 Action Surge", "动作如潮", "Action Surge"],
      sequence: "lawrenceActionSurge",
      tier: 3,
      defaultEnabled: true,
      requiresTarget: false,
      selfTarget: true,
      crpMode: "overlay-safe",
      notes: "动作如潮以折射力场、石尘爆发和轻微镜头震动表现爆发行动。"
    }
  ]
};
